// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","parentId":"@@/global-layout","id":"1"},"2":{"path":"/ecosystem","parentId":"@@/global-layout","id":"2"},"3":{"path":"/bridge","parentId":"@@/global-layout","id":"3"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__Home__index" */'@/pages/Home/index.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__Ecosystem__index" */'@/pages/Ecosystem/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__Bridge__index" */'@/pages/Bridge/index.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'/Users/keene/workspace2/btc-l2-web3-interface/src/layouts/index.tsx')),
},
  };
}
